const temas = [
  'Amor de Casal',
  'Amizade',
  'Agradecimento',
  'Ânimo',
  'Amor de Deus',
  'Amor ao Próximo',
  'Amigo',
  'Ajuda ao Próximo',
  'Amor',
  'Adoração a Deus',
  'Ação de Graças',
  'Agradecimento pela Vida',
  'Arrependimento',
  'Angústia',
  'Adoração',
  'Ano Novo',
  'Ajuda para Casais',
  'Avivamento',
  'A Segunda Vinda de Jesus',
  'Aceitar Jesus',
  'Arrebatamento',
  'Amor Próprio',
  'Ajuda',
  'Aliança',
  'Autoridade',
  'Aflição',
  'Amigos',
  'Água',
  'Ansiedade',
  'Adolescentes',
  'Arca da Aliança',
  'Aniversário',
  'A Lei de Deus',
  'Águia',
  'Aniversário de Pastor',
  'Amar a Deus',
  'Agradecimento a Deus',
  'Alma',
  'Anjos',
  'Adversidade',
  'Amor verdadeiro',
  'Aparência',
  'Amor Incondicional',
  'Atitude',
  'Anticristo',
  'Aborto',
  'Àrvore',
  'Amaldiçoar',
  'Abundância',
  'Altar',
  'Amor Fraternal',
  'Animais',
  'Adultério',
  'Arca de Noé',
  'Apostasia',
  'Armagedon',
  'Armadura de Deus',
  'Aniversário de Casamento',
  'Aprendizado',
  'Abertura de Culto',
  'Abandono',
  'Aliança com Deus',
  'Autoestima',
  'Adorador',
  'Ateísmo',
  'Aceitação',
  'Anátema',
  'Adoção',
  'Amabilidade',
  'Azeite',
  'Adoradores',
  'Álcool',
  'Alegria',
  'Arcanjo',
  'Abraço',
  'Amargura',
  'Árvore da Vida',
  'Andorinhas',
  'Adoração ao Senhor',
  'Argumentos',
  'Batismo',
  'Batismo nas Águas',
  'Bênção',
  'Boa Noite',
  'Batismo no Espírito Santo',
  'Bom Dia',
  'Buscar a Deus',
  'Bênçãos de Deus',
  'Bondade',
  'Beleza',
  'Boas Vindas',
  'Batalha Espiritual',
  'Batalha',
  'Boa Semana',
  'Boas-Novas',
  'Bíblia',
  'Brechas',
  'Bençãos',
  'Batismo com Fogo',
  'Babilônia',
  'Bebidas Alcoólicas',
  'Bens Materiais',
  'Bispos',
  'Boca',
  'Batizado',
  'Bom Ânimo',
  'Benignidade',
  'Casamento',
  'Cura',
  'Casais',
  'Comunhão com os Irmãos',
  'Conforto',
  'Ceia do Senhor',
  'Coragem',
  'Confiar no Senhor',
  'Confiança',
  'Compromisso',
  'Consagração',
  'Criança',
  'Clamor',
  'Coração',
  'Cuidado de Deus',
  'Cuidado',
  'Casa de Deus',
  'Caminho',
  'Cruz',
  'Ciúmes',
  'Conquista',
  'Céu',
  'Conhecimento',
  'Chamado de Deus',
  'Carne',
  'Choro',
  'Consolo',
  'Confessar os Pecados',
  'Chuva',
  'Coração Quebrantado',
  'Comunhão',
  'Crer',
  'Casa do Senhor',
  'Coração Puro',
  'Caridade',
  'Comunhão com Deus',
  'Conselhos',
  'Corpo Humano',
  'Conselhos Financeiros',
  'Corpo de Cristo',
  'Consequências',
  'Calma',
  'Correção',
  'Crer em Jesus',
  'Compaixão',
  'Calúnia',
  'Culpa',
  'Cobiça',
  'Crescimento Espiritual',
  'Consolar',
  'Contenda',
  'Cordeiro de Deus',
  'Confissão',
  'Casa',
  'Cantar',
  'Caminhos',
  'Cidade',
  'Consciência',
  'Crescimento',
  'Consolação',
  'Congregação',
  'Cristo',
  'Circuncisão',
  'Contentamento',
  'Confusão',
  'Cânticos',
  'Concupiscência',
  'Criação',
  'Celebração',
  'Carpinteiro',
  'Criacionismo',
  'Crítica',
  'Conversação',
  'Cristianismo',
  'Caverna',
  'Crença',
  'Corrida Cristã',
  'Comunidade',
  'Dízimo',
  'Dia dos Pais',
  'Depressão',
  'Descansar em Deus',
  'Dons Espirituais',
  'Despedida',
  'Desânimo',
  'Divórcio',
  'Deus',
  'Descanso',
  'Doação',
  'Doença',
  'Dança',
  'Dúvida',
  'Desobediência',
  'Dinheiro',
  'Domínio próprio',
  'Decisão',
  'Dedicação',
  'Demônios',
  'Desejar o Mal',
  'Doutrina',
  'Dor',
  'Deserto',
  'Diabo',
  'Desespero',
  'Discernimento',
  'Disciplina',
  'Davi',
  'Divindade de Jesus Cristo',
  'Dívidas',
  'Discipulado',
  'Dons',
  'Drogas',
  'Decepção',
  'Desistir',
  'Disciplina Espiritual',
  'Deuses',
  'Desonestidade',
  'Dar',
  'Discípulos',
  'Domínio',
  'Devoção',
  'Disciplina de Deus',
  'Desgosto',
  'Deficientes',
  'Defeitos',
  'Disputas',
  'Desculpas',
  'Encorajamento',
  'Espírito Santo',
  'Esperar',
  'Evangelismo',
  'Esperança',
  'Enfermidade',
  'Ensino',
  'Edificação',
  'Estudar a Bíblia',
  'Esposa',
  'Encorajamento',
  'Espiritismo',
  'Exortação',
  'Escolhido',
  'Eu Sou',
  'Espírito',
  'Espíritos Imundos',
  'Evangelho',
  'Educação das Crianças',
  'Excelência',
  'Exército',
  'Entendimento',
  'Estilo de Vida',
  'Entusiasmo',
  'Expiação',
  'Espinhos',
  'Exaltação a Deus',
  'Eternidade',
  'Expectativas',
  'Espada',
  'Emprego',
  'Egoísmo',
  'Força',
  'Família',
  'Filhos',
  'Fortalecimento',
  'Felicidade',
  'Falsidade',
  'Fidelidade',
  'Fim dos Tempos',
  'Falsos Profetas',
  'Falecimento',
  'Filhos de Deus',
  'Fé',
  'Fazer o Bem',
  'Flores',
  'Fogo',
  'Fim do mundo',
  'Frutos',
  'Fofoca',
  'Feitiçaria',
  'Formatura',
  'Fornicação',
  'Fome de Deus',
  'Falar em Línguas',
  'Fraqueza',
  'Fogo de Deus',
  'Fogo Consumidor',
  'Frutos do Espírito',
  'Fortaleza',
  'Filho do Homem',
  'Falsos Cristos',
  'Fiel',
  'Futuro',
  'Festa',
  'Fracasso',
  'Filho Pródigo',
  'Fome',
  'Fidelidade de Deus',
  'Fornalha',
  'Fugir',
  'gratidão',
  'Graça',
  'Gravidez',
  'Grandeza de Deus',
  'Governo',
  'Guerreiro',
  'Guerra Espiritual',
  'Glória de Deus',
  'Guardar o Coração',
  'Gratidão ao Senhor',
  'Galardão',
  'Ganhar Almas',
  'Guerra',
  'Glória',
  'Guardar o Sábado',
  'Generosidade',
  'Grande Tribulação',
  'Grandeza',
  'Graças',
  'Geração',
  'Glorificação',
  'Ganhar',
  'Genealogia',
  'Gentileza',
  'Honra',
  'Humildade',
  'Homem de Deus',
  'Hipocrisia',
  'Humilhação',
  'Honrar',
  'Herança',
  'Heresia',
  'Honestidade',
  'História',
  'Hábitos',
  'Hospitalidade',
  'Harmonia',
  'Incentivo',
  'Idolatria',
  'Intimidade',
  'Intercessão',
  'Inveja',
  'Inferno',
  'Igreja',
  'Identidade',
  'Injustiça',
  'Irmãos',
  'Impossível',
  'Imagens',
  'Ingratidão',
  'Ídolos',
  'Imitadores de Cristo',
  'Imoralidade',
  'Israel',
  'Inimigos de Deus',
  'Inimigos',
  'Integridade',
  'Ira',
  'Inteligência',
  'Insegurança',
  'Iniquidade',
  'Igualdade',
  'Inspiração',
  'Insultos',
  'Importância',
  'Impurezas',
  'Impostos',
  'Indiferença',
  'Inspiração',
  'Infidelidade',
  'Influência',
  'Incenso',
  'Ide',
  'Jovens',
  'Jejum',
  'Jesus me Ama',
  'Justiça de Deus',
  'Julgar',
  'Jesus Cristo',
  'Julgar',
  'Justiça',
  'Justo',
  'Julgamento',
  'Justiça Divina',
  'Jerusalém',
  'Jogos de azar',
  'Justificação',
  'Juramentos',
  'Jeová',
  'Juízo Final',
  'Juízo',
  'Luto',
  'Livramento',
  'Louvor',
  'Livre-arbítrio',
  'Língua',
  'Luz',
  'Lúcifer',
  'Louvor',
  'Liderança',
  'Luz do Mundo',
  'Leão',
  'Libertação',
  'Liberdade',
  'Ler a Bíblia',
  'Livro da Vida',
  'Louvar',
  'Loucura',
  'Lágrimas',
  'Luxúria',
  'Longanimidade',
  'Ladrão',
  'Língua dos Anjos',
  'Lázaro',
  'Linguagem Grosseira',
  'Línguas de Fogo',
  'Lealdade',
  'Lei',
  'Motivação',
  'Mulher Sábia',
  'Mentira',
  'Mulher',
  'Morte',
  'Medo',
  'Missões',
  'Mudança de vida',
  'Misericórdia',
  'Morte de Jesus',
  'Milagres de Jesus',
  'Maria',
  'Meditação',
  'Mente',
  'Marido',
  'Mal',
  'Mãos',
  'Maldição',
  'Marca da Besta',
  'Mansidão',
  'Maturidade',
  'Mães',
  'Música',
  'Mocidade',
  'Murmuração',
  'Morte',
  'Milagres',
  'Mar Vermelho',
  'Mundo',
  'Mortos',
  'Marido e Mulher',
  'Multiplicação',
  'Mordomia',
  'Marca',
  'Mundano',
  'Mar',
  'Monstros na Bíblia',
  'Mediador',
  'Mão direita',
  'Monstros Marinhos',
  'Nunca desistir',
  'Namoro',
  'Natal',
  'Namorados',
  'Nascimento',
  'Não temas',
  'Natureza',
  'Noivado',
  'Nova criatura',
  'Noite',
  'Nova Aliança',
  'Nascer de Novo',
  'Nascimento',
  'Noiva',
  'Nação',
  'Nome de Jesus',
  'Nova Jerusalém',
  'Necessidades',
  'Oração',
  'Os sonhos de Deus',
  'O Tempo de Deus',
  'Oferta',
  'Ouvir a voz de Deus',
  'Obediência aos Pais',
  'Oração de madrugada',
  'Orgulho',
  'Obedecer',
  'Otimismo',
  'Os Últimos Dias',
  'Ódio',
  'Ousadia',
  'Obra',
  'Olhos',
  'Obreiro',
  'Ouro',
  'Olhos do Senhor',
  'Oração Contrária?',
  'Orientação',
  'Organização',
  'Onipotência',
  'Oportunidades',
  'Os Dez Mandamentos',
  'Ocultismo',
  'Ovelhas',
  'Ouvidos',
  'Próximo',
  'Palavras',
  'Perdão',
  'Palavra de Deus',
  'Poder da Oração',
  'Proteção',
  'Palavra de oferta',
  'Pastor',
  'Pais',
  'Paz',
  'Propósito',
  'Promessas de Deus',
  'Páscoa',
  'Presença de Deus',
  'Paciência',
  'Poder da Palavra',
  'Prosperidade',
  'Pecado',
  'Papel da Mulher',
  'Providência de Deus',
  'Planos',
  'Perseverança',
  'Política',
  'Participar dos cultos',
  'Provação',
  'Poder de Decisão',
  'Perseguição',
  'Promessas Bíblicas',
  'Preguiça',
  'Primícias',
  'Pensamentos',
  'Papel do homem',
  'Prostituição',
  'Parabéns',
  'Preocupação',
  'Poder',
  'Porta',
  'Profecia',
  'Primeiro Amor',
  'Pureza',
  'Pão',
  'Profeta',
  'Pentecostes',
  'Parentes',
  'Povo',
  'Prioridades',
  'Paixão',
  'Perfeito',
  'Pedra',
  'Passado',
  'Preocupar-se Menos',
  'Pés',
  'Preservação das Escrituras',
  'Purificação',
  'Posição Social',
  'Progresso',
  'Pêsames',
  'Pai da Mentira',
  'Pregação',
  'Pobreza',
  'Pai Nosso',
  'Quebrantamento',
  'Quaresma',
  'Querubins',
  'Restauração',
  'Recompensa',
  'Recomeço',
  'Ressurreição',
  'Renovar',
  'Rios',
  'Respeito',
  'Reino de Deus',
  'Rocha',
  'Reino dos Céus',
  'Reconciliação',
  'Reflexão',
  'Religião',
  'Renovação',
  'Restituição',
  'Refúgio',
  'Rebeldia',
  'Relações sexuais',
  'Roubar',
  'Racismo',
  'Raiva',
  'Revelação',
  'Redenção',
  'Riquezas',
  'Reino',
  'Relacionamentos',
  'Repreensão',
  'Rejeição',
  'Regeneração',
  'Reputação',
  'Risco',
  'Retidão',
  'Superação',
  'Salvação',
  'Sonhos',
  'Santa Ceia',
  'Servir',
  'Suicídio',
  'Santidade',
  'Segurança',
  'Silêncio',
  'Saúde',
  'Santificação',
  'Sorriso',
  'Sexo',
  'Sofrimento',
  'Sabedoria',
  'Semente',
  'Solidão',
  'Servo',
  'Solucionar Problemas',
  'Sacrifício',
  'Sábado',
  'Socorro',
  'Sangue',
  'Saudade',
  'Submissão',
  'Satanás',
  'Sucesso',
  'Soberania',
  'Sol',
  'Sangue de Jesus',
  'Segunda Vinda de Cristo',
  'Santo',
  'Sinceridade',
  'Sono',
  'Solteiros',
  'Sacerdote',
  'Sal da Terra',
  'Sinais',
  'Santuário',
  'Superstição',
  'Sacrifícios',
  'Sorte',
  'Serpente',
  'Sábio',
  'Súplica',
  'Soberba',
  'Stress',
  'Segurança Eterna',
  'Simplicidade',
  'Surpresa',
  'Trabalho',
  'Tristeza',
  'Tatuagem',
  'Tempo',
  'Trabalhar para Deus',
  'Traição',
  'Tentação',
  'Transformação',
  'Temor à Deus',
  'Tribulação',
  'Trindade',
  'Trevas',
  'Tranquilidade',
  'Testemunho',
  'Tempestade',
  'Tesouros',
  'Tolo',
  'Talentos',
  'Testemunhar',
  'Temor',
  'Transfiguração',
  'União',
  'Unidade',
  'Unção',
  'Última Ceia',
  'Vitória',
  'Volta de Jesus',
  'Vontade de Deus',
  'Vencer',
  'Vaso',
  'Vida Eterna',
  'Vencedor',
  'Vida Nova',
  'Vingança',
  'Vestes',
  'Visão',
  'Vaidade',
  'Velhice',
  'Verdade',
  'Vontade',
  'Véu',
  'Viúvas',
  'Vento',
  'Vinho',
  'Viúva',
  'Vida',
  'Violência',
  'Ventre',
  'Vergonha',
  'Zelo'
]

export const filterTemas = (alph: string) => {
  if (alph !== 'TODOS') {
    return temas
      .filter((tema) => {
        if (
          tema.substr(0, 1) === alph.toUpperCase() ||
          tema.substr(0, 1) === alph.toLowerCase()
        ) {
          return tema
        }
      })
      .sort()
  } else {
    return temas.sort()
  }
}

export default temas
